version: 2
updates:
  # Main SortVision app dependencies
  - package-ecosystem: "npm"
    directory: "/SortVision"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    # Increase PR limit for active development
    open-pull-requests-limit: 15
    # Custom commit message for better tracking
    commit-message:
      prefix: "⬆️ deps"
      prefix-development: "⬆️ dev-deps"
      include: "scope"
    # PR settings
    pull-request-branch-name:
      separator: "/"
    reviewers:
      - "alienx5499"
    # Advanced grouping for better organization
    groups:
      # Critical security updates (high priority)
      security-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
      
      # React ecosystem updates
      react-ecosystem:
        patterns:
          - "react*"
          - "@types/react*"
          - "react-dom*"
          - "@vitejs/plugin-react*"
        update-types:
          - "minor"
          - "patch"
      
      # Build tools and bundlers
      build-tools:
        patterns:
          - "vite*"
          - "rollup*"
          - "@rollup/*"
          - "esbuild*"
          - "postcss*"
          - "autoprefixer*"
        update-types:
          - "minor"
          - "patch"
      
      # Styling and UI dependencies
      ui-dependencies:
        patterns:
          - "tailwindcss*"
          - "@tailwindcss/*"
          - "lucide-react*"
          - "framer-motion*"
          - "clsx*"
          - "class-variance-authority*"
        update-types:
          - "minor"
          - "patch"
      
      # Development tools
      dev-tools:
        patterns:
          - "eslint*"
          - "@eslint/*"
          - "prettier*"
          - "@typescript-eslint/*"
          - "typescript*"
          - "@types/*"
        update-types:
          - "minor"
          - "patch"
      
      # Testing dependencies
      testing-dependencies:
        patterns:
          - "vitest*"
          - "@testing-library/*"
          - "jest*"
          - "@jest/*"
          - "cypress*"
          - "playwright*"
        update-types:
          - "minor"
          - "patch"
      
      # Analytics and monitoring
      analytics:
        patterns:
          - "@vercel/analytics*"
          - "@vercel/speed-insights*"
          - "sentry*"
          - "@sentry/*"
        update-types:
          - "minor"
          - "patch"
      
      # Minor utility updates
      utilities:
        patterns:
          - "lodash*"
          - "uuid*"
          - "date-fns*"
          - "axios*"
          - "zod*"
        update-types:
          - "patch"
      
      # All other dependencies (lowest priority)
      other-dependencies:
        patterns:
          - "*"
        update-types:
          - "patch"

    # Selective ignoring for stability
    ignore:
      # Major version bumps for core dependencies (require manual review)
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
      - dependency-name: "vite"
        update-types: ["version-update:semver-major"]
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]
      - dependency-name: "tailwindcss"
        update-types: ["version-update:semver-major"]
      - dependency-name: "eslint"
        update-types: ["version-update:semver-major"]
      
      # Specific problematic versions (if any)
      - dependency-name: "node-gyp"
        versions: ["8.x", "9.x"]
      
      # Experimental or beta versions
      - dependency-name: "*"
        versions: ["*-alpha", "*-beta", "*-rc*", "*-canary*"]

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "10:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "⬆️ ci"
      include: "scope"
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Docker dependencies (if using Docker in the future)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "11:00"
      timezone: "UTC"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "⬆️ docker"
      include: "scope"

enable-beta-ecosystems: true
